### ISSUE TITLE
$this->clients all contain the last opened connection in each Connection instance

### ISSUE THREAD

**Issue by clarkk** [arthurkushman/php-wss#13] opened 2018-08-28 07:10 UTC
I need to store data on each client like session id etc

In the `onMessage` method I have this line `$key = array_search($recv, $this->clients);` but it always returns `1` ??

Even when there are multiply connected clients.. When a client sends a message to the server `1` is returned? 

All clients are storing their data on client with key 1

```
class ServerHandler extends WebSocket {
    public $pathParams = [':entity', ':context', ':token'];
    private $clients        = [];
    private $client_data    = [];

    public function onOpen(ConnectionContract $conn){
        end($this->clients);
        $key = key($this->clients) + 1;
        
        $this->clients[$key] = $conn;
        echo 'Connection opend, total clients: ' . count($this->clients) . '('.$key.')' . PHP_EOL;
    }

    public function onMessage(ConnectionContract $recv, $msg){
        $key = array_search($recv, $this->clients);
        
        echo 'Received message ('.$key.'):  ' . $msg . PHP_EOL;
        
        $json = json_decode($msg, true);
        
        if(isset($json['sid'])){
            $this->client_data[$key]['sid'] = $json['sid'];
        }
        
        $recv->send($msg);
    }
}
```

**Comment by clarkk** [comment] 2018-08-28 09:02
If I print `$this->clients` in `onMessage` it seems like the same resource is in all values

```
Array
(
    [1] => WSSC\Components\Connection Object
        (
            [socketConnection:WSSC\Components\Connection:private] => Resource id #20
        )

    [2] => WSSC\Components\Connection Object
        (
            [socketConnection:WSSC\Components\Connection:private] => Resource id #20
        )

)
```

**Comment by clarkk** [comment] 2018-08-28 09:32
Have changed the title.. I think this might be a bug

More code and output

```
class ServerHandler extends WebSocket {
	public $pathParams = [':entity', ':context', ':token'];
	private $clients        = [];
	private $client_data    = [];
	
	public function onOpen(ConnectionContract $conn){
		end($this->clients);
		$key = key($this->clients) + 1;
		
		$this->clients[$key] = $conn;
		echo 'Connection opend, total clients: ' . count($this->clients) . '('.$key.')' . "\n";
	}
	
	public function onMessage(ConnectionContract $recv, $msg){
		$key = null;
		foreach($this->clients as $k => $value){
			if($recv === $value){
				$key = $k;
				break;
			}
		}
		
		if($key === null){
			echo "Err: Client not found!\n";
		}
		
		echo 'Received message ('.$key.'):  ' . $msg . PHP_EOL;
		
		$json = json_decode($msg, true);
		
		if(isset($json['sid'])){
			$this->client_data[$key]['sid'] = $json['sid'];
			echo "sid: ".$json['sid']."\n";
		}
		
		if(isset($json['browser'])){
			$this->client_data[$key]['browser'] = $json['browser'];
			echo "browser: ".$json['browser']."\n";
		}
		
		echo "\n";
		
		$recv->send($msg);
	}
}
```

Two different connections but only receiving on the first client
```
Connection opend, total clients: 1(1)
Received message (1):  {"sid":"4nnlvagg103jm1v4rjs5nqdii6","browser":"chrome"}
sid: 4nnlvagg103jm1v4rjs5nqdii6
browser: chrome

Connection opend, total clients: 2(2)
Received message (1):  {"sid":"fc5qhkf0e37nq12a8h0rdav000","browser":"firefox"}
sid: fc5qhkf0e37nq12a8h0rdav000
browser: firefox
```

javascript
```
function Websocket(){
	var socket, self = this;
	
	this.connect = function(){
		if(socket){
			socket.close();
		}
		
		socket = new WebSocket('wss://websocket.'+HOST+':8443');
		
		socket.onopen = function(e){
			this.send(JSON.stringify({
				sid : self.get_session_id(),
				browser : get_browser().name
			}));
			console.log('WS connection established!');
		};
		
		socket.onclose = function(e){
			console.log('WS connection closed!')
		};
		
		socket.onerror = function(e){
			console.log('WS an error occurred!');
			console.log('Err: '+e.data);
		};
		
		socket.onmessage = function(e){
			console.log('Message from server: '+e.data);
		};
	};
	
	/*
	
	
	*/
	//socket.send('the message');
	
	this.get_session_id = function(){
		return document.cookie.match(/PHPSESSID=([^;]+)/)[1];
	};
}
```

**Comment by clarkk** [comment] 2018-08-28 14:13
https://github.com/arthurkushman/php-wss/issues/6

**Comment by arthurkushman** [comment] 2018-08-29 12:35
Closing as duplicate of #6 - the patch with fix  https://github.com/arthurkushman/php-wss/releases/tag/1.3.6
Thx

**Closed by arthurkushman** 2018-08-29 12:35 UTC
Labels: bug
